const wykonczenia = [
  {
    name: "do formatu",
    group: "winyle",
    kod: "df",
    description: "Wycięcie materiału do żądanego formatu.",
    detailsDtp: [
      "Powiększ obraz o 0,3 cm na każdą krawędzi, na której wystepuje to wykończenie. Np. wykończenie na około do formatu, wymiar netto: 100x100, po powiększeniu 100,6x100,6",
      "Dodaj 1px obrys wokół całej grafiki w kolorze 50/50/50/10.",
      "Dodaj 2 cm białego obszaru roboczego do jednej z krawędzi.",
      "Na dodanym białym obszarze umieść nazwę pliku - skrót Ctrl+F12.",
      "Dodaj kwadracik informujący o rodzaju wysyłki i umieść na nim dzień daty produkcji.",
      "Zapisz plik zgodnie z naszym standardem dodając końcówkę _TwojeInicjały_RIP",
    ],
    dtpExceptions: [
      "Folie i papiery powiękaszmy o 0,3 cm na stronę już na etapie sprawdzania plików.",
    ],
    additionalInfo: [],
    exapmlesMaterials: ["bpwl510", "mesh270", "artg", "4+0 bkhv640", "bbkl"],
    detailsDw: ["wziąć", "wyciąć"],
    dwExceptions: [""],
  },
  {
    name: "do formatu",
    group: "sublimacja",
    kod: "df",
    description: "Wycięcie materiału do żądanego formatu.",
    detailsDtp: [
      "Dodaj 1px obrys wokół całej grafiki w kolorze 50/50/50/10.",
      "Dodaj 2 cm białego obszaru roboczego do jednej z krawędzi.",
      "Na dodanym białym obszarze umieść nazwę pliku - skrót Ctrl+F12.",
      "Dodaj kwadracik informujący o rodzaju wysyłki i umieść na nim dzień daty produkcji.",
      "Zapisz plik zgodnie z naszym standardem dodając końcówkę _TwojeInicjały_RIP",
    ],
    dtpExceptions: [
      "Folie i papiery powiękaszmy o 0,3 cm na stronę już na etapie sprawdzania plików.",
    ],
    additionalInfo: [],
    exapmlesMaterials: [
      "flg115B",
      "bmat215",
      "flgMesh119",
      "ledtex",
      "poliM225",
    ],
    detailsDw: ["wziąć", "wyciąć"],
    dwExceptions: [""],
  },
  {
    name: "do formatu",
    group: "mw",
    kod: "df",
    description:
      "Wycięcie materiału do żądanego formatu. MW posiada narzędzie nazywane fotobą służące do sprawnego wycinania formatek.",
    detailsDtp: [
      "Obraz został powiększony o 0,3 cm na stronę na sprawdzaniu.",
      "Z akcji DTP wybierz odpowiednią szerokość fotoby.",
      "Na dodanym białym obszarze umieść nazwę pliku - skrót Ctrl+F12.",
      "Dodaj kwadracik informujący o rodzaju wysyłki i umieść na nim dzień daty produkcji.",
      "Zapisz plik zgodnie z naszym standardem dodając końcówkę _TwojeInicjały_RIP",
    ],
    dtpExceptions: [
      "Sprawdź czy folie zostały powiększone na etapie sprawdzania!",
      "Folia one way vision (fowv) z racji swojej budowy nie jest wycinana na fotobie - dodajemy jej tylko pasery narożnikowe i opis.",
    ],
    additionalInfo: [],
    exapmlesMaterials: ["fmgl", "fwlk", "fpl0G", "pp15", "pclp"],
    detailsDw: ["wziąć", "wyciąć"],
    dwExceptions: [""],
  },
  {
    name: "zgrzew",
    group: "winyle",
    kod: "z",
    description: "Krawędzie zgrzane w celu wzmocnienia.",
    detailsDtp: [
      "Powiększamy obraz nieproporcjonalnie o 0,5 cm na każdą krawędź, na której występuje wykończenie. Np. wymiar netto 100x100, wykończenie na około zgrzew - po powiększeniu 101x101.",
      "Dodaj 1px obrys wokół całej grafiki w kolorze 50/50/50/10.",
      "Dodaj 3 cm białego obszaru roboczego do każdej z krawędzi, na której występuje wykończenie.",
      "Jeżeli w danej pozycji występują inne wykończenia na którejś z krawędzi przejdź do nich przed kolejnym krokiem.",
      "Dodaj 1px obrys wokół całej grafiki w kolorze 50/50/50/10.",
      "Na dodanym białym obszarze umieść nazwę pliku - skrót Ctrl+F12.",
      "Dodaj kwadracik informujący o rodzaju wysyłki i umieść na nim dzień daty produkcji.",
      "Zapisz plik zgodnie z naszym standardem dodając końcówkę _TwojeInicjały_RIP",
    ],
    dtpExceptions: [
      "Zgrzew na produktach z drukiem 4+4 przygotowujemy inaczej - patrz zgrzew 4+4",
    ],
    additionalInfo: [],
    exapmlesMaterials: [
      "bpwl510",
      "mesh270",
      "4+0 bklt",
      "4+0 bkhv",
      "blam510",
    ],
    detailsDw: ["wziąć", "wyciąć"],
    dwExceptions: [""],
  },
  {
    name: "zgrzew + oczka",
    group: "winyle",
    kod: "oz",
    description: "Krawędzie zgrzane w celu wzmocnienia + oczka na zgrzewie.",
    detailsDtp: [
      "Powiększamy obraz nieproporcjonalnie o 0,5 cm na każdą krawędź, na której występuje wykończenie. Np. wymiar netto 100x100, wykończenie na około zgrzew - po powiększeniu 101x101.",
      "Dodaj 1px obrys wokół całej grafiki w kolorze 50/50/50/10.",
      "Umieść oczko na początku krawędzi.",
      "Powiel umieszone oczko i przenieś je na koniec krawędzi.",
      "Powiel pierwsze oczko odpowiednią ilość razy.",
      "Zaznacz wszystkie oczka i rozmieść równomiernie korzystając z narzędzia Rozmieść poziomo/pionowo",
      "Dodaj 3 cm białego obszaru roboczego do każdej z krawędzi, na której występuje wykończenie.",
      "Spłaszcz obraz (Ctrl+Alt+Q)",
      "Powiel 6 ostatnich kroków na wszystkich krawędziach, na których występuje to wykończenie.",
      "Jeżeli w danej pozycji występują inne wykończenia na którejś z krawędzi przejdź do nich przed kolejnym krokiem.",
      "Dodaj 1px obrys wokół całej grafiki w kolorze 50/50/50/10.",
      "Na dodanym białym obszarze umieść nazwę pliku - skrót Ctrl+F12.",
      "Dodaj kwadracik informujący o rodzaju wysyłki i umieść na nim dzień daty produkcji.",
      "Zapisz plik zgodnie z naszym standardem dodając końcówkę _TwojeInicjały_RIP",
    ],
    dtpExceptions: [
      "Zgrzew na produktach z drukiem 4+4 przygotowujemy inaczej - patrz zgrzew 4+4",
    ],
    additionalInfo: [
      "Oczko znajdziesz w folderze PLIKI NA START",
      "Przed umieszczeniem oczka w pliku produkcyjnym upewnij się, że oczko ma taką samą rodzielczość jak plik.",
      "Środek standardowego oczka powinien być oddalony od krawędzi wymiaru brutto o 2cm.",
    ],
    exapmlesMaterials: [
      "bpwl510",
      "mesh270",
      "4+0 bklt",
      "4+0 bkhv",
      "blam510",
    ],
    detailsDw: ["wziąć", "wyciąć"],
    dwExceptions: [""],
  },
  {
    name: "oczka",
    group: "winyle",
    kod: "o",
    description: "Wydruk docięty do formatu + oczka na krawędziach.",
    detailsDtp: [
      "Powiększ obraz nieproporcjonalnie o 0,3 cm na każdą krawędzi, na której wystepuje to wykończenie. Np. wykończenie na około do formatu, wymiar netto: 100x100, po powiększeniu 100,6x100,6",
      "Dodaj 1px obrys wokół całej grafiki w kolorze 50/50/50/10.",
      "Umieść oczko na początku krawędzi.",
      "Powiel umieszone oczko i przenieś je na koniec krawędzi.",
      "Powiel pierwsze oczko odpowiednią ilość razy.",
      "Zaznacz wszystkie oczka i rozmieść równomiernie korzystając z narzędzia Rozmieść poziomo/pionowo",
      "Spłaszcz obraz (Ctrl+Alt+Q)",
      "Powiel 5 ostatnich kroków na wszystkich krawędziach, na których występuje to wykończenie.",
      "Jeżeli w danej pozycji występują inne wykończenia na którejś z krawędzi przejdź do nich przed kolejnym krokiem.",
      "Dodaj 1px obrys wokół całej grafiki w kolorze 50/50/50/10.",
      "Dodaj 2 cm białego obszaru roboczego do jednej z krawędzi.",
      "Na dodanym białym obszarze umieść nazwę pliku - skrót Ctrl+F12.",
      "Dodaj kwadracik informujący o rodzaju wysyłki i umieść na nim dzień daty produkcji.",
      "Zapisz plik zgodnie z naszym standardem dodając końcówkę _TwojeInicjały_RIP",
    ],
    dtpExceptions: [
      "Zgrzew na produktach z drukiem 4+4 przygotowujemy inaczej - patrz zgrzew 4+4",
    ],
    additionalInfo: [
      "Oczko znajdziesz w folderze PLIKI NA START",
      "Przed umieszczeniem oczka w pliku produkcyjnym upewnij się, że oczko ma taką samą rodzielczość jak plik.",
      "Środek standardowego oczka powinien być oddalony od krawędzi wymiaru brutto o 2cm.",
    ],
    exapmlesMaterials: [
      "bpwl510",
      "mesh270",
      "4+0 bklt",
      "4+0 bkhv",
      "blam510",
    ],
    detailsDw: ["wziąć", "wyciąć"],
    dwExceptions: [""],
    dhInfo: [
      "Wykończenie może występować również na sublimacji ale zwykle łączone jest z wykończeniami tj. np .taśma wzmacniająca od tyłu.",
    ],
  },
  {
    name: "kedar",
    group: "winyle",
    kod: "k",
    description: "Wydruk docięty do formatu + wszyty kedar.",
    detailsDtp: [
      "Na krawędzi, na której występuje dane wykończenie nie powiększamy obrazu.",
      "Jeżeli w danej pozycji występują inne wykończenia na którejś z krawędzi przejdź do nich przed kolejnym krokiem.",
      "Dodaj 1px obrys wokół całej grafiki w kolorze 50/50/50/10.",
      "Dodaj 2 cm białego obszaru roboczego do jednej z krawędzi.",
      "Na dodanym białym obszarze umieść nazwę pliku - skrót Ctrl+F12.",
      "Dodaj kwadracik informujący o rodzaju wysyłki i umieść na nim dzień daty produkcji.",
      "Zapisz plik zgodnie z naszym standardem dodając końcówkę _TwojeInicjały_RIP",
    ],
    dtpExceptions: [],
    additionalInfo: [
      "Kedar to jedno z nielicznych wykończeń przy ktorych nie powiększamy obrazu.",
    ],
    exapmlesMaterials: ["bpwl510", "flg115B", "bkhv640", "bmat215", "mesh270"],
    detailsDw: ["wziąć", "wyciąć"],
    dwExceptions: [""],
  },
  {
    name: "kedar",
    group: "sublimacja",
    kod: "k",
    description: "Wydruk docięty do formatu + wszyty kedar.",
    detailsDtp: [
      "Na krawędzi, na której występuje dane wykończenie nie powiększamy obrazu.",
      "Jeżeli w danej pozycji występują inne wykończenia na którejś z krawędzi przejdź do nich przed kolejnym krokiem.",
      "Dodaj 1px obrys wokół całej grafiki w kolorze 50/50/50/10.",
      "Dodaj 2 cm białego obszaru roboczego do jednej z krawędzi.",
      "Na dodanym białym obszarze umieść nazwę pliku - skrót Ctrl+F12.",
      "Dodaj kwadracik informujący o rodzaju wysyłki i umieść na nim dzień daty produkcji.",
      "Zapisz plik zgodnie z naszym standardem dodając końcówkę _TwojeInicjały_RIP",
    ],
    dtpExceptions: [],
    additionalInfo: [
      "Kedar to jedno z nielicznych wykończeń przy ktorych nie powiększamy obrazu.",
    ],
    exapmlesMaterials: ["bpwl510", "flg115B", "bkhv640", "bmat215", "mesh270"],
    detailsDw: ["wziąć", "wyciąć"],
    dwExceptions: [""],
  },
  {
    name: "szycie",
    group: "sublimacja",
    kod: "s",
    description: "Materiał zawijany i przeszywany na maszynie.",
    detailsDtp: [
      "Na dodanym białym obszarze umieść nazwę pliku - skrót Ctrl+F12.",
      "Dodaj kwadracik informujący o rodzaju wysyłki i umieść na nim dzień daty produkcji.",
      "Zapisz plik zgodnie z naszym standardem dodając końcówkę _TwojeInicjały_RIP",
    ],
    dtpExceptions: [],
    additionalInfo: [""],
    exapmlesMaterials: [],
    detailsDw: [],
    dwExceptions: [""],
  },
  {
    name: "szycie",
    group: "winyle",
    kod: "s",
    description: "Materiał zawijany i przeszywany na maszynie.",
    detailsDtp: [
      "Na dodanym białym obszarze umieść nazwę pliku - skrót Ctrl+F12.",
      "Dodaj kwadracik informujący o rodzaju wysyłki i umieść na nim dzień daty produkcji.",
      "Zapisz plik zgodnie z naszym standardem dodając końcówkę _TwojeInicjały_RIP",
    ],
    dtpExceptions: [],
    additionalInfo: [""],
    exapmlesMaterials: [],
    detailsDw: [],
    dwExceptions: [""],
  },
  {
    name: "oczka w narożnikach",
    group: "winyle",
    kod: "on",
    description: "Pochodna wykończenia oczka.",
    detailsDtp: ["Patrz wykończenie: oczka"],
    dtpExceptions: [],
    additionalInfo: [""],
    exapmlesMaterials: [],
    detailsDw: [],
    dwExceptions: [""],
    dhInfo: ["Patrz wykończenie: oczka"],
  },
  {
    name: "oczka w narożnikach + zgrzew",
    group: "winyle",
    kod: "onz",
    description: "Pochodna wykończenia oczka + zgrzew.",
    detailsDtp: ["Patrz wykończenie: oczka + zgrzew"],
    dtpExceptions: [],
    additionalInfo: [""],
    exapmlesMaterials: [],
    detailsDw: [],
    dwExceptions: [""],
    dhInfo: ["Patrz wykończenie: oczka + zgrzew"],
  },
  {
    name: "oczka w narożnikach + szycie",
    group: "winyle",
    kod: "onz",
    description: "Pochodna wykończenia oczka + szycie.",
    detailsDtp: ["Patrz wykończenie: oczka + szycie"],
    dtpExceptions: [],
    additionalInfo: [""],
    exapmlesMaterials: [],
    detailsDw: [],
    dwExceptions: [""],
    dhInfo: ["Patrz wykończenie: oczka + szycie"],
  },
  {
    name: "podwójny zgrzew",
    group: "winyle",
    kod: "pz",
    description: "Krawędzie zaginane dwukrotnie i zgrzewane.",
    detailsDtp: ["Podwójny zgrzew"],
    dtpExceptions: [],
    additionalInfo: [""],
    exapmlesMaterials: [],
    detailsDw: [],
    dwExceptions: [""],
    dhInfo: ["Krawędzie zaginane dwukrotnie i zgrzewane."],
  },
  {
    name: "podwójny zgrzew + oczka",
    group: "winyle",
    kod: "opz",
    description:
      "Krawędzie zaginane dwukrotnie i zgrzewane + oczka na zgrzewie",
    detailsDtp: [
      "Patrz wykończenie: podwójny zgrzew.",
      "Patrz wykończenie: zgrzew + oczka.",
    ],
    dtpExceptions: [],
    additionalInfo: [""],
    exapmlesMaterials: [],
    detailsDw: [],
    dwExceptions: [""],
    dhInfo: ["Krawędzie zaginane dwukrotnie i zgrzewane + oczka na zgrzewie."],
  },
  {
    name: "szycie + oczka",
    group: "winyle",
    kod: "os",
    description: "Krawędzie zaginane i przeszywane + oczka na szyciu",
    detailsDtp: ["Patrz wykończenie: zgrzew + oczka."],
    dtpExceptions: [],
    additionalInfo: [""],
    exapmlesMaterials: [],
    detailsDw: [],
    dwExceptions: [""],
    dhInfo: ["Krawędzie zaginane i przeszywane + oczka na przeszyciu."],
  },
  {
    name: "szycie + oczka",
    group: "sublimacja",
    kod: "os",
    description:
      "Krawędzie zaginane i przeszywane + oczka na szyciu. Alternatywa do samych oczek i do oczek na taśmie wzmacniającej - lepsza niż same oczka jednak nie tak wytrzymała jak oczka na taśmie.",
    detailsDtp: ["Patrz wykończenie: zgrzew + oczka."],
    dtpExceptions: [],
    additionalInfo: [""],
    exapmlesMaterials: [],
    detailsDw: [],
    dwExceptions: [""],
    dhInfo: [
      "Krawędzie zaginane i przeszywane + oczka na szyciu. Alternatywa do samych oczek i do oczek na taśmie wzmacniającej - lepsza niż same oczka jednak nie tak wytrzymała jak oczka na taśmie.",
    ],
  },
  {
    name: "do kształtu",
    group: "winyle",
    kod: "wk",
    description:
      "Krawędzie wycinane do kształtu tak jak wykończenie do formatu.",
    detailsDtp: ["Patrz wykończenie: zgrzew + oczka."],
    dtpExceptions: [],
    additionalInfo: [""],
    exapmlesMaterials: [],
    detailsDw: [],
    dwExceptions: [""],
    dhInfo: ["Krawędzie wycinane do kształtu tak jak wykończenie do formatu."],
  },
  {
    name: "do kształtu",
    group: "sublimacja",
    kod: "wk",
    description:
      "Krawędzie wycinane do kształtu tak jak wykończenie do formatu. W zależności od rozmiaru i kształtu krawędzie mogą być wycinane na gorąco lub nie.",
    detailsDtp: ["Patrz wykończenie: zgrzew + oczka."],
    dtpExceptions: [],
    additionalInfo: [""],
    exapmlesMaterials: [],
    detailsDw: [],
    dwExceptions: [""],
    dhInfo: [
      "Krawędzie wycinane do kształtu tak jak wykończenie do formatu.",
      "W zależności od rozmiaru i kształtu krawędzie mogą być wycinane na gorąco lub nie.",
    ],
  },
  {
    name: "do kształtu",
    group: "mw",
    kod: "wk",
    description:
      "Krawędzie wycinane do kształtu tak jak wykończenie do formatu. Niektóre grafiki mogą być wycięte do kształtu bez konieczności użycia plotera tnącego.",
    detailsDtp: ["Patrz wykończenie: zgrzew + oczka."],
    dtpExceptions: [],
    additionalInfo: [""],
    exapmlesMaterials: [],
    detailsDw: [],
    dwExceptions: [""],
    dhInfo: [
      "Krawędzie wycinane do kształtu tak jak wykończenie do formatu.",
      "Niektóre grafiki mogą być wycięte do kształtu bez konieczności użycia plotera tnącego.",
    ],
  },
  {
    name: "do kształtu + zgrzew",
    group: "winyle",
    kod: "wkz",
    description: "Krawędzie wycinane do kształtu następnie zgrzewane.",
    detailsDtp: ["Zgrzew do kształtu"],
    dtpExceptions: [],
    additionalInfo: [
      "W większości przypadków wykończenie to zostanie zastąpione wykończeniem do kształtu + szycie - będzie tak, ze względu na dużą problematyczność i niską trwałość zgrzewów innych niż w linii prostej.",
    ],
    exapmlesMaterials: [],
    detailsDw: [],
    dwExceptions: [""],
    dhInfo: [
      "Krawędzie wycinane do kształtu następnie zgrzewane.",
      "W większości przypadków wykończenie to zostanie zastąpione wykończeniem do kształtu + szycie - będzie tak, ze względu na dużą problematyczność i niską trwałość zgrzewów innych niż w linii prostej.",
    ],
  },
  {
    name: "do kształtu + oczka",
    group: "winyle",
    kod: "wko",
    description: "Krawędzie wycinane do kształtu + oczka.",
    detailsDtp: ["Do kształtu + oczka"],
    dtpExceptions: [],
    additionalInfo: [],
    exapmlesMaterials: [],
    detailsDw: [],
    dwExceptions: [""],
    dhInfo: ["Krawędzie wycinane do kształtu + oczka."],
  },
  {
    name: "do kształtu + zgrzew + oczka",
    group: "winyle",
    kod: "wkoz",
    description:
      "Krawędzie wycinane do kształtu, zaginane i zgrzewane, następnie oczkowane. To wykończenie jest możliwe tylko przy określych kształtach - głownie opierających się na liniach prostych. Lepszą i częściej stosowaną alternatywą tego wykończenia jest do kształtu + szycie + oczka.",
    detailsDtp: ["Do kształtu + oczka"],
    dtpExceptions: [],
    additionalInfo: [],
    exapmlesMaterials: [],
    detailsDw: [],
    dwExceptions: [""],
    dhInfo: [
      "Krawędzie wycinane do kształtu, zaginane i zgrzewane, następnie oczkowane.",
      " To wykończenie jest możliwe tylko przy określych kształtach - głownie opierających się na liniach prostych.",
      "Lepszą i częściej stosowaną alternatywą tego wykończenia jest wykończenie do kształtu + szycie + oczka.",
    ],
  },
  {
    name: "do kształtu + oczka",
    group: "sublimacja",
    kod: "wko",
    description: "Krawędzie wycinane do kształtu + oczka.",
    detailsDtp: ["Do kształtu + oczka"],
    dtpExceptions: [],
    additionalInfo: [],
    exapmlesMaterials: [],
    detailsDw: [],
    dwExceptions: [""],
    dhInfo: [
      "Krawędzie wycinane do kształtu + oczka.",
      "Oczka bez dodatkowego wzmocnienia na materiałach sublimacyjnych są mało trwałe - warto dodać wzmocnienie z taśmy wzmacniającej lub ewentualnie przeszycie.",
    ],
  },
  {
    name: "do kształtu + szycie",
    group: "winyle",
    kod: "wks",
    description: "Krawędzie wycinane do kształtu + szycie.",
    detailsDtp: ["Do kształtu + szycie"],
    dtpExceptions: [],
    additionalInfo: ["Przygotowanie tak samo jak do kształtu + zgrzew."],
    exapmlesMaterials: [],
    detailsDw: [],
    dwExceptions: [],
    dhInfo: [
      "Krawędzie wycinane do kształtu + szycie.",
      "Najbezpieczniejsze i najlepsze wzmocnienie krawędzi w przypadku wycinania do kształtu.",
    ],
  },
  {
    name: "do kształtu + szycie",
    group: "sublimacja",
    kod: "wks",
    description: "Krawędzie wycinane do kształtu + szycie.",
    detailsDtp: ["Do kształtu + szycie"],
    dtpExceptions: [],
    additionalInfo: [],
    exapmlesMaterials: [],
    detailsDw: [],
    dwExceptions: [],
    dhInfo: ["Krawędzie wycinane do kształtu + szycie."],
  },
  {
    name: "do kształtu + szycie + oczka",
    group: "winyle",
    kod: "wkos",
    description: "Krawędzie wycinane do kształtu + szycie + oczka.",
    detailsDtp: ["Do kształtu + szycie + oczka"],
    dtpExceptions: [],
    additionalInfo: [],
    exapmlesMaterials: [],
    detailsDw: [],
    dwExceptions: [],
    dhInfo: [
      "Krawędzie wycinane do kształtu + szycie + oczka.",
      "Najbezpieczniejsze i najlepsze wzmocnienie krawędzi w przypadku wycinania do kształtu i oczek.",
    ],
  },
  {
    name: "do kształtu + szycie + oczka",
    group: "sublimacja",
    kod: "wkos",
    description: "Krawędzie wycinane do kształtu + szycie + oczka.",
    detailsDtp: ["Do kształtu + szycie + oczka"],
    dtpExceptions: [],
    additionalInfo: [],
    exapmlesMaterials: [],
    detailsDw: [],
    dwExceptions: [],
    dhInfo: [
      "Krawędzie wycinane do kształtu + szycie + oczka.",
      "Szycie jest kiepskim wzmocnieniem w przypadku oczek na materiałąch sublimacyjnych - zaproponuj wykończenie taśmą wzmacniającą.",
    ],
  },
  {
    name: "rzep",
    group: "winyle",
    kod: "rz",
    description:
      "Krawędzie wycinane do formatu + rzep od spodu lub od strony grafiki.",
    detailsDtp: ["Patrz wykończenie do formatu."],
    dtpExceptions: [],
    additionalInfo: [],
    exapmlesMaterials: [],
    detailsDw: [],
    dwExceptions: [],
    dhInfo: [
      "Krawędzie wycinane do formatu + rzep od spodu lub od strony grafiki.",
      "Rzep w standardzie umieszczany jest na back'u, jeżeli chcesz, aby rzep został umieszony na fronice zawrzyj stosowną informację w szczegółach wykończenia.",
    ],
  },
  {
    name: "rzep",
    group: "sublimacja",
    kod: "rz",
    description:
      "Przyszycie rzepu, następnie zagięcie go na back/front i ponowne przeszycie.",
    detailsDtp: ["Rzep na sublimacji"],
    dtpExceptions: [],
    additionalInfo: [],
    exapmlesMaterials: [],
    detailsDw: [],
    dwExceptions: [],
    dhInfo: [
      "Przyszycie rzepu, następnie zagięcie go na back/front i ponowne przeszycie.",
      "Rzep w standardzie umieszczany jest na back'u, jeżeli chcesz, aby rzep został umieszony na fronice zawrzyj stosowną informację w szczegółach wykończenia.",
    ],
  },
  {
    name: "taśma silikonowa",
    group: "winyle",
    kod: "ts",
    description:
      "Krawędź wzmocniona taśmą silikonową używaną do montażu w specjalnych systemach.",
    detailsDtp: ["Taśma silikonowa"],
    dtpExceptions: [],
    additionalInfo: [],
    exapmlesMaterials: [],
    detailsDw: [],
    dwExceptions: [],
    dhInfo: [
      "Krawędź wzmocniona taśmą silikonową używaną do montażu w specjalnych systemach.",
      "W poligrafie powinien znaleźć się zewnętrzny wymiar ramy - taki rozmiar powinien mieć też plik produkcyjny.",
    ],
  },
  {
    name: "taśma silikonowa",
    group: "sublimacja",
    kod: "ts",
    description:
      "Krawędź wzmocniona taśmą silikonową używaną do montażu w specjalnych systemach.",
    detailsDtp: ["Taśma silikonowa"],
    dtpExceptions: ["Na materiale ledtex dodajemy 0,5 cm w pukncie x."],
    additionalInfo: [],
    exapmlesMaterials: [],
    detailsDw: [],
    dwExceptions: [],
    dhInfo: [
      "Krawędź wzmocniona taśmą silikonową używaną do montażu w specjalnych systemach.",
      "W poligrafie powinien znaleźć się zewnętrzny wymiar ramy - taki rozmiar powinien mieć też plik produkcyjny.",
    ],
  },
  {
    name: "taśma wzmacniająca od przodu",
    group: "sublimacja",
    kod: "twp",
    description:
      "Krawędź wzmocniona złożoną w pół taśmą wzmacniającą. Przypis 'od przodu' jest opcjonalny i możesz spotkać też zapis 'taśma wzmacniająca' i będzie on równoznaczny z powyższym wykończeniem.",
    detailsDtp: ["Taśma wzmacniająca"],
    dtpExceptions: [
      "Zwróć uwagę na szerokość taśmy - standard to 7 cm, czyli na pół 3,5 cm.",
    ],
    additionalInfo: [
      "Taśma wzmacniająca i taśma wzmacniająca od tyłu to dwa różne wykończenia!",
    ],
    exapmlesMaterials: [],
    detailsDw: [],
    dwExceptions: [],
    dhInfo: [
      "Wzmocnienie krawędzi taśmą składaną na pół.",
      "Taśma widoczna jest zarówno na froncie jak i na backu wydruku.",
      "Standardem jest taśma wzmacniająca o szerokości 7 cm, czyli tłumacząc to na język produkcyjny 3,5 cm (taśma jest składana na pół).",
      "Jeżeli chcesz użyć innej szerokości taśmy wpisz stosowną informację w szczegółach wykończenia oraz dodaj do kodu '=szerokość_taśmy_w_cm'",
    ],
  },
  {
    name: "taśma wzmacniająca od tyłu",
    group: "sublimacja",
    kod: "twt",
    description:
      "Krawędź wzmocniona taśmą. Wykończenie niewidoczne od frontu wydruku.",
    detailsDtp: ["Taśma wzmacniająca"],
    dtpExceptions: [
      "Zwróć uwagę na szerokość taśmy - standard to 7 cm, czyli na pół 3,5 cm.",
    ],
    additionalInfo: [
      "Taśma wzmacniająca i taśma wzmacniająca od tyłu to dwa różne wykończenia!",
      "Jeżeli w wykończeniu zawarta jest informacja o innej szerokości niż standardowe 3,5 cm w kodzie powinien znaleźć się dopisek '=szerokość_taśmy_w_cm'.",
    ],
    exapmlesMaterials: [],
    detailsDw: [],
    dwExceptions: [],
    dhInfo: [
      "Wzmocnienie krawędzi taśmą przyszytą od tyłu.",
      "Taśma widoczna jest tylko na backu.",
      "Krawędź wydruku zabezpieczona jest przeszyciem z taśmą dzięki czemu materiał nie ulegnie pruciu.",
    ],
  },
  {
    name: "taśma wzmacniająca od tyłu + oczka",
    group: "sublimacja",
    kod: "twto",
    description:
      "Krawędź wzmocniona taśmą + oczka. Taśma niewidoczna od frontu wydruku.",
    detailsDtp: ["Taśma wzmacniająca od tyłu + oczka"],
    dtpExceptions: [],
    additionalInfo: [
      "Taśma wzmacniająca i taśma wzmacniająca od tyłu to dwa różne wykończenia!",
      "Handlowiec może zamieścić odległość między oczkami w kodzie rozszerzając go o dopisek '=odległość_między_oczkami_w_cm'",
    ],
    exapmlesMaterials: [],
    detailsDw: [],
    dwExceptions: [],
    dhInfo: [
      "Wzmocnienie krawędzi taśmą przyszytą od tyłu + oczka.",
      "Taśma widoczna jest tylko na backu.",
      "Krawędź wydruku zabezpieczona jest przeszyciem z taśmą dzięki czemu materiał nie ulegnie pruciu.",
      "Standardem odległości między oczkami jest 50 cm. Jeżeli chcesz, aby oczka rozmieszczone były w innej odległości rozrzesz kod o dopisek '=odległość_między_oczkami_w_cm' i zawrzyj stosowną informację w szczegółach wykończenia.",
    ],
  },
  {
    name: "cięcie na gorąco",
    group: "sublimacja",
    kod: "cg",
    description:
      "Wycinanie do formatu specjalnym nożem z podgrzewanym ostrzem.",
    detailsDtp: [],
    dtpExceptions: [],
    additionalInfo: ["Wykończenie może być łączone z wycinaniem do kształtu."],
    exapmlesMaterials: [],
    detailsDw: [],
    dwExceptions: [],
    dhInfo: [
      "Wycinanie do formatu nożem na gorąco - zapobiega pruciu się materiału w produktach sublimacyjnych.",
    ],
  },

  //produkty

  {
    name: "Beachflag F",
    group: "produkt",
    kod: "F/rozmiar_dostawca",
    description: "Beachflag w kształcie F.",
    detailsDtp: [
      "Upewnij się, że wszystkie linie siatki nie zostały przycięte na etapie sprawdzania.",
      "Dodaj opis za pomocą skrótu CTRL + F12.",
      "Opis powinien znaleźć się w lewym górnym narożniku chyba, że rękaw jest po prawej stronie - wtedy opis też po prawej.",
      "Obok opisu umieść pole transportu w odpowiednim kolorze wraz z dniem produkcji.",
      "Zapisz plik z dopiskiem '_inicjały_rip'",
    ],
    dtpExceptions: [],
    additionalInfo: [
      "Impozycja flag F to zawsze (jeżeli ilość powtórzeń na to pozwala) dwie flagi jedna obrócona 0 180 stopni.",
    ],
    exapmlesMaterials: ["flg115B", "bmat215"],
    sizes: [
      { size: "S_ST", netto: "80x175", brutto: "92x181" },
      { size: "M_ST", netto: "105x235", brutto: "117x241" },
      { size: "L_ST", netto: "130x295", brutto: "141x301" },
      { size: "XL_ST", netto: "163x382", brutto: "176x389" },
      { size: "S_BG", netto: "60x175", brutto: "67x181" },
      { size: "M_BG", netto: "95x240", brutto: "99x244" },
      { size: "L_BG", netto: "110x320", brutto: "119x324" },
      { size: "XL_BG", netto: "100x430", brutto: "108x434" },
    ],
    detailsDw: [],
    dwExceptions: [],
    dhInfo: ["W kodzie uzupełnij rozmiar."],
    szwalnia: {
      description:
        "Beachflag w kształcie F. Występują w różnych wariantach cenowych: ST i BG. Każdy z wariantów wystepuje w róznych rozmiarach.",
      steps: [
        {
          description:
            "Wycinamy flagę po paserach ( na grafice zaznaczone na niebiesko). Jedyny paser jaki zostaje to ten od rękawa ( zaznaczony na różowo). Jest to konieczne, ponieważ pozostawiona linia wyznacza bok, który należy obrzucić na overlocku.",
          img: ["1"],
          templates: ["1"],
          warrning: [],
          time: {
            S_ST: { sub: 1, szw: 20 },
            M_ST: { sub: 10, szw: 20 },
            L_ST: { sub: 10, szw: 20 },
            XL_ST: { sub: 10, szw: 20 },
            S_BG: { sub: 1, szw: 20 },
            M_BG: { sub: 10, szw: 20 },
            L_BG: { sub: 10, szw: 20 },
            XL_BG: { sub: 10, szw: 20 },
          },
        },
        {
          description:
            "Obrzucamy wewnętrzną część rękawa na overlocku tak, aby ściąć cały paser.",
          img: ["2a", "2b"],
          templates: ["2"],
          warrning: [
            "Dobierz nici pod kolor flagi, chyba że rękaw jest w jednym kolorze; na overlocku używamy nici o grubości 100 i 80",
            "Należy zwrócić szczególną uwagę czy obrzucony rękaw jest estetyczny oraz czy materiał nie został zbytnio ścięty.",
          ],
          time: {
            S_ST: { sub: 2, szw: 20 },
            M_ST: { sub: 10, szw: 20 },
            L_ST: { sub: 10, szw: 20 },
            XL_ST: { sub: 10, szw: 20 },
            S_BG: { sub: 1, szw: 20 },
            M_BG: { sub: 10, szw: 20 },
            L_BG: { sub: 10, szw: 20 },
            XL_BG: { sub: 10, szw: 20 },
          },
        },
        {
          description:
            "Standardowa BF ma rękaw po lewej stronie. Gdy rozłożymy wydruk, tak jak na grafice to mamy pewność, że strona frontowa jest na wierzchu. Możemy zacząć szyć, flagi tego typu szyjemy jedną igłą. Zaczynamy od dołu. Układamy rękaw na brzegu wydruku. Zaczynamy zszywać ze sobą, pamiętając aby zostawić 2 cm od krawędzi. Zatrzymujemy się 12-13cm przed końcem (góra flagi).",
          img: ["3a", "3b"],
          warrning: [
            "Rękaw przyszyty przy samej krawędzi może się łatwo oderwać.",
          ],
          time: {
            S_ST: { sub: 3, szw: 20 },
            M_ST: { sub: 10, szw: 20 },
            L_ST: { sub: 10, szw: 20 },
            XL_ST: { sub: 10, szw: 20 },
            S_BG: { sub: 1, szw: 20 },
            M_BG: { sub: 10, szw: 20 },
            L_BG: { sub: 10, szw: 20 },
            XL_BG: { sub: 10, szw: 20 },
          },
        },
        {
          description:
            "Szykujemy element z taśmy sztandarowej o wymiarach: 5x12. Należy pośrodku zrobić wycięcie o wysokości 2 cm, tak jak na grafice.",
          img: ["4"],
          warrning: [],
          time: {
            S_ST: { sub: 4, szw: 20 },
            M_ST: { sub: 10, szw: 20 },
            L_ST: { sub: 10, szw: 20 },
            XL_ST: { sub: 10, szw: 20 },
            S_BG: { sub: 1, szw: 20 },
            M_BG: { sub: 10, szw: 20 },
            L_BG: { sub: 10, szw: 20 },
            XL_BG: { sub: 10, szw: 20 },
          },
        },
        {
          description:
            "Przenosimy się na górę flagi. Przygotowaną w kroku 4 taśmę składamy według zagięcia. Następnie podkładamy pod obydwie warstwy (flagę i rękaw) tak, aby od wcięcia w taśmie do końca FLAGI zostały 2 cm. Pozostały materiał w dalszych krokach posłuży do wykończenia wydruku.",
          img: ["5"],
          warrning: [],
          time: {
            S_ST: { sub: 5, szw: 20 },
            M_ST: { sub: 10, szw: 20 },
            L_ST: { sub: 10, szw: 20 },
            XL_ST: { sub: 10, szw: 20 },
            S_BG: { sub: 1, szw: 20 },
            M_BG: { sub: 10, szw: 20 },
            L_BG: { sub: 10, szw: 20 },
            XL_BG: { sub: 10, szw: 20 },
          },
        },
        {
          description:
            "Podłożoną w poprzednim kroku taśmę przeszywamy do wcięcia i mocujemy.",
          img: ["6"],
          warrning: [],
          time: {
            S_ST: { sub: 10, szw: 20 },
            M_ST: { sub: 10, szw: 20 },
            L_ST: { sub: 10, szw: 20 },
            XL_ST: { sub: 10, szw: 20 },
            S_BG: { sub: 1, szw: 20 },
            M_BG: { sub: 10, szw: 20 },
            L_BG: { sub: 10, szw: 20 },
            XL_BG: { sub: 10, szw: 20 },
          },
        },
        {
          description:
            "Z reguły rękaw jest trochę dłuższy niż sama flaga, należy ściąć jego nadmiar na równi z wydrukiem.",
          img: ["7"],
          warrning: [],
          time: {
            S_ST: { sub: 10, szw: 20 },
            M_ST: { sub: 10, szw: 20 },
            L_ST: { sub: 10, szw: 20 },
            XL_ST: { sub: 10, szw: 20 },
            S_BG: { sub: 1, szw: 20 },
            M_BG: { sub: 10, szw: 20 },
            L_BG: { sub: 10, szw: 20 },
            XL_BG: { sub: 10, szw: 20 },
          },
        },
        {
          description:
            "Rozkładamy na płasko rękaw przyszyty do flagi razem z 1 warstwą taśmy, przeszywamy w lini prostej oraz mocujemy nasze wzmocnienie.",
          img: ["8"],
          warrning: [],
          time: {
            S_ST: { sub: 10, szw: 20 },
            M_ST: { sub: 10, szw: 20 },
            L_ST: { sub: 10, szw: 20 },
            XL_ST: { sub: 10, szw: 20 },
            S_BG: { sub: 1, szw: 20 },
            M_BG: { sub: 10, szw: 20 },
            L_BG: { sub: 10, szw: 20 },
            XL_BG: { sub: 10, szw: 20 },
          },
        },
        {
          description:
            "Obracamy flagę na tylną stronę. Przenosimy się na dół. Tutaj również musimy wszyć wzmocnienie z taśmy. Używamy jak poprzednio taśmy o szerokości 5cm. Przykładamy ją do rozłożonego na płasko rękawa (zaczynamy od boku obrzuconego na overlocku). 2cm od dołu zostawiamy na wykończenie, a  2,5 cm od boku zostawiamy, aby w dalszym kroku móc wszyć tam sznurek.",
          img: ["9a", "9b"],
          warrning: [],
          time: {
            S_ST: { sub: 10, szw: 20 },
            M_ST: { sub: 10, szw: 20 },
            L_ST: { sub: 10, szw: 20 },
            XL_ST: { sub: 10, szw: 20 },
            S_BG: { sub: 1, szw: 20 },
            M_BG: { sub: 10, szw: 20 },
            L_BG: { sub: 10, szw: 20 },
            XL_BG: { sub: 10, szw: 20 },
          },
        },
        {
          description:
            "Na taśmę podkładamy złożoną na pół czarna, wąska tasiemkę. Powinna mieć 7,5cm na płasko i wystawać poza flagę 2 cm.",
          img: ["10"],
          warrning: [],
          time: {
            S_ST: { sub: 10, szw: 20 },
            M_ST: { sub: 10, szw: 20 },
            L_ST: { sub: 10, szw: 20 },
            XL_ST: { sub: 10, szw: 20 },
            S_BG: { sub: 1, szw: 20 },
            M_BG: { sub: 10, szw: 20 },
            L_BG: { sub: 10, szw: 20 },
            XL_BG: { sub: 10, szw: 20 },
          },
        },
        {
          description:
            "Jesteśmy nadal na dole flagi. Podwijamy pozostawione 2cm materiału, aby estetycznie wykończyć krawędź. Przeszywamy razem z tasiemką.",
          img: ["11"],
          warrning: [],
          time: {
            S_ST: { sub: 10, szw: 20 },
            M_ST: { sub: 10, szw: 20 },
            L_ST: { sub: 10, szw: 20 },
            XL_ST: { sub: 10, szw: 20 },
            S_BG: { sub: 1, szw: 20 },
            M_BG: { sub: 10, szw: 20 },
            L_BG: { sub: 10, szw: 20 },
            XL_BG: { sub: 10, szw: 20 },
          },
        },
        {
          description:
            "Na ściętym boku od tyłu wszywamy sznurek. Potrzebny nam będzie taki o średnicy 4mm. Zawijamy 1 cm flagi, dokładamy do tego sznurek i razem zawijamy na następny 1 cm, przeszywamy kierując się ku górze.",
          img: ["12a", "12b", "12c"],
          warrning: [],
          time: {
            S_ST: { sub: 10, szw: 20 },
            M_ST: { sub: 10, szw: 20 },
            L_ST: { sub: 10, szw: 20 },
            XL_ST: { sub: 10, szw: 20 },
            S_BG: { sub: 1, szw: 20 },
            M_BG: { sub: 10, szw: 20 },
            L_BG: { sub: 10, szw: 20 },
            XL_BG: { sub: 10, szw: 20 },
          },
        },
        {
          description:
            "Wracamy na front flagi. Na dole przy tasiemce powinien pozostać kawałek materiału, należy go zawinąć do środka i przeszyć. Od tego momentu składamy rękaw na flagę i zaczynamy zszywać razem trzymając się obrzuconego boku.",
          img: ["13a", "13b", "13c"],
          warrning: [
            "Jeżeli rękaw ma inny kolor niż reszta flagi, dolną nitkę dobieramy pod niego.",
          ],
          time: {
            S_ST: { sub: 10, szw: 20 },
            M_ST: { sub: 10, szw: 20 },
            L_ST: { sub: 10, szw: 20 },
            XL_ST: { sub: 10, szw: 20 },
            S_BG: { sub: 1, szw: 20 },
            M_BG: { sub: 10, szw: 20 },
            L_BG: { sub: 10, szw: 20 },
            XL_BG: { sub: 10, szw: 20 },
          },
        },
        {
          description:
            "Koniecznie zamykamy koniec tunelu na górze. Inaczej nie będzie możliwe założenie finalnego produktu na maszt.",
          img: ["14"],
          warrning: [],
          time: {
            S_ST: { sub: 10, szw: 20 },
            M_ST: { sub: 10, szw: 20 },
            L_ST: { sub: 10, szw: 20 },
            XL_ST: { sub: 10, szw: 20 },
            S_BG: { sub: 1, szw: 20 },
            M_BG: { sub: 10, szw: 20 },
            L_BG: { sub: 10, szw: 20 },
            XL_BG: { sub: 10, szw: 20 },
          },
        },
        {
          description:
            "W wszytą tasiemkę wkładamy gumkę. W zależności od wielkości flagi: <300cm - 70cm gumka, >300cm - 140cm gumka",
          img: ["15"],
          warrning: [],
          time: {
            S_ST: { sub: 10, szw: 30 },
            M_ST: { sub: 10, szw: 25 },
            L_ST: { sub: 10, szw: 20 },
            XL_ST: { sub: 10, szw: 20 },
            S_BG: { sub: 1, szw: 20 },
            M_BG: { sub: 10, szw: 20 },
            L_BG: { sub: 10, szw: 20 },
            XL_BG: { sub: 10, szw: 20 },
          },
        },
      ],
    },
  },
];

export default wykonczenia;
