const wykonczenia = [
  {
    name: "do formatu",
    group: "winyle",
    kod: "df",
    description: "Wycięcie materiału do żądanego formatu.",
    detailsDtp: [
      "Powiększ obraz o 0,3 cm na każdą krawędzi, na której wystepuje to wykończenie. Np. wykończenie na około do formatu, wymiar netto: 100x100, po powiększeniu 100,6x100,6",
      "Dodaj 1px obrys wokół całej grafiki w kolorze 50/50/50/10.",
      "Dodaj 2 cm białego obszaru roboczego do jednej z krawędzi.",
      "Na dodanym białym obszarze umieść nazwę pliku - skrót Ctrl+F12.",
      "Dodaj kwadracik informujący o rodzaju wysyłki i umieść na nim dzień daty produkcji.",
      "Zapisz plik zgodnie z naszym standardem dodając końcówkę _TwojeInicjały_RIP",
    ],
    dtpExceptions: [
      "Folie i papiery powiękaszmy o 0,3 cm na stronę już na etapie sprawdzania plików.",
    ],
    additionalInfo: [],
    exapmlesMaterials: ["bpwl510", "mesh270", "artg", "4+0 bkhv640", "bbkl"],
    detailsDw: ["wziąć", "wyciąć"],
    dwExceptions: [""],
  },
  {
    name: "do formatu",
    group: "sublimacja",
    kod: "df",
    description: "Wycięcie materiału do żądanego formatu.",
    detailsDtp: [
      "Dodaj 1px obrys wokół całej grafiki w kolorze 50/50/50/10.",
      "Dodaj 2 cm białego obszaru roboczego do jednej z krawędzi.",
      "Na dodanym białym obszarze umieść nazwę pliku - skrót Ctrl+F12.",
      "Dodaj kwadracik informujący o rodzaju wysyłki i umieść na nim dzień daty produkcji.",
      "Zapisz plik zgodnie z naszym standardem dodając końcówkę _TwojeInicjały_RIP",
    ],
    dtpExceptions: [
      "Folie i papiery powiękaszmy o 0,3 cm na stronę już na etapie sprawdzania plików.",
    ],
    additionalInfo: [],
    exapmlesMaterials: [
      "flg115B",
      "bmat215",
      "flgMesh119",
      "ledtex",
      "poliM225",
    ],
    detailsDw: ["wziąć", "wyciąć"],
    dwExceptions: [""],
  },
  {
    name: "do formatu",
    group: "mw",
    kod: "df",
    description:
      "Wycięcie materiału do żądanego formatu. MW posiada narzędzie nazywane fotobą służące do sprawnego wycinania formatek.",
    detailsDtp: [
      "Obraz został powiększony o 0,3 cm na stronę na sprawdzaniu.",
      "Z akcji DTP wybierz odpowiednią szerokość fotoby.",
      "Na dodanym białym obszarze umieść nazwę pliku - skrót Ctrl+F12.",
      "Dodaj kwadracik informujący o rodzaju wysyłki i umieść na nim dzień daty produkcji.",
      "Zapisz plik zgodnie z naszym standardem dodając końcówkę _TwojeInicjały_RIP",
    ],
    dtpExceptions: [
      "Sprawdź czy folie zostały powiększone na etapie sprawdzania!",
      "Folia one way vision (fowv) z racji swojej budowy nie jest wycinana na fotobie - dodajemy jej tylko pasery narożnikowe i opis.",
    ],
    additionalInfo: [],
    exapmlesMaterials: ["fmgl", "fwlk", "fpl0G", "pp15", "pclp"],
    detailsDw: ["wziąć", "wyciąć"],
    dwExceptions: [""],
  },
  {
    name: "zgrzew",
    group: "winyle",
    kod: "z",
    description: "Krawędzie zgrzane w celu wzmocnienia.",
    detailsDtp: [
      "Powiększamy obraz nieproporcjonalnie o 0,5 cm na każdą krawędź, na której występuje wykończenie. Np. wymiar netto 100x100, wykończenie na około zgrzew - po powiększeniu 101x101.",
      "Dodaj 1px obrys wokół całej grafiki w kolorze 50/50/50/10.",
      "Dodaj 3 cm białego obszaru roboczego do każdej z krawędzi, na której występuje wykończenie.",
      "Jeżeli w danej pozycji występują inne wykończenia na którejś z krawędzi przejdź do nich przed kolejnym krokiem.",
      "Dodaj 1px obrys wokół całej grafiki w kolorze 50/50/50/10.",
      "Na dodanym białym obszarze umieść nazwę pliku - skrót Ctrl+F12.",
      "Dodaj kwadracik informujący o rodzaju wysyłki i umieść na nim dzień daty produkcji.",
      "Zapisz plik zgodnie z naszym standardem dodając końcówkę _TwojeInicjały_RIP",
    ],
    dtpExceptions: [
      "Zgrzew na produktach z drukiem 4+4 przygotowujemy inaczej - patrz zgrzew 4+4",
    ],
    additionalInfo: [],
    exapmlesMaterials: [
      "bpwl510",
      "mesh270",
      "4+0 bklt",
      "4+0 bkhv",
      "blam510",
    ],
    detailsDw: ["wziąć", "wyciąć"],
    dwExceptions: [""],
  },
  {
    name: "zgrzew + oczka",
    group: "winyle",
    kod: "oz",
    description: "Krawędzie zgrzane w celu wzmocnienia + oczka na zgrzewie.",
    detailsDtp: [
      "Powiększamy obraz nieproporcjonalnie o 0,5 cm na każdą krawędź, na której występuje wykończenie. Np. wymiar netto 100x100, wykończenie na około zgrzew - po powiększeniu 101x101.",
      "Dodaj 1px obrys wokół całej grafiki w kolorze 50/50/50/10.",
      "Umieść oczko na początku krawędzi.",
      "Powiel umieszone oczko i przenieś je na koniec krawędzi.",
      "Powiel pierwsze oczko odpowiednią ilość razy.",
      "Zaznacz wszystkie oczka i rozmieść równomiernie korzystając z narzędzia Rozmieść poziomo/pionowo",
      "Dodaj 3 cm białego obszaru roboczego do każdej z krawędzi, na której występuje wykończenie.",
      "Spłaszcz obraz (Ctrl+Alt+Q)",
      "Powiel 6 ostatnich kroków na wszystkich krawędziach, na których występuje to wykończenie.",
      "Jeżeli w danej pozycji występują inne wykończenia na którejś z krawędzi przejdź do nich przed kolejnym krokiem.",
      "Dodaj 1px obrys wokół całej grafiki w kolorze 50/50/50/10.",
      "Na dodanym białym obszarze umieść nazwę pliku - skrót Ctrl+F12.",
      "Dodaj kwadracik informujący o rodzaju wysyłki i umieść na nim dzień daty produkcji.",
      "Zapisz plik zgodnie z naszym standardem dodając końcówkę _TwojeInicjały_RIP",
    ],
    dtpExceptions: [
      "Zgrzew na produktach z drukiem 4+4 przygotowujemy inaczej - patrz zgrzew 4+4",
    ],
    additionalInfo: [
      "Oczko znajdziesz w folderze PLIKI NA START",
      "Przed umieszczeniem oczka w pliku produkcyjnym upewnij się, że oczko ma taką samą rodzielczość jak plik.",
      "Środek standardowego oczka powinien być oddalony od krawędzi wymiaru brutto o 2cm.",
    ],
    exapmlesMaterials: [
      "bpwl510",
      "mesh270",
      "4+0 bklt",
      "4+0 bkhv",
      "blam510",
    ],
    detailsDw: ["wziąć", "wyciąć"],
    dwExceptions: [""],
  },
  {
    name: "oczka",
    group: "winyle",
    kod: "o",
    description: "Wydruk docięty do formatu + oczka na krawędziach.",
    detailsDtp: [
      "Powiększ obraz nieproporcjonalnie o 0,3 cm na każdą krawędzi, na której wystepuje to wykończenie. Np. wykończenie na około do formatu, wymiar netto: 100x100, po powiększeniu 100,6x100,6",
      "Dodaj 1px obrys wokół całej grafiki w kolorze 50/50/50/10.",
      "Umieść oczko na początku krawędzi.",
      "Powiel umieszone oczko i przenieś je na koniec krawędzi.",
      "Powiel pierwsze oczko odpowiednią ilość razy.",
      "Zaznacz wszystkie oczka i rozmieść równomiernie korzystając z narzędzia Rozmieść poziomo/pionowo",
      "Spłaszcz obraz (Ctrl+Alt+Q)",
      "Powiel 5 ostatnich kroków na wszystkich krawędziach, na których występuje to wykończenie.",
      "Jeżeli w danej pozycji występują inne wykończenia na którejś z krawędzi przejdź do nich przed kolejnym krokiem.",
      "Dodaj 1px obrys wokół całej grafiki w kolorze 50/50/50/10.",
      "Dodaj 2 cm białego obszaru roboczego do jednej z krawędzi.",
      "Na dodanym białym obszarze umieść nazwę pliku - skrót Ctrl+F12.",
      "Dodaj kwadracik informujący o rodzaju wysyłki i umieść na nim dzień daty produkcji.",
      "Zapisz plik zgodnie z naszym standardem dodając końcówkę _TwojeInicjały_RIP",
    ],
    dtpExceptions: [
      "Zgrzew na produktach z drukiem 4+4 przygotowujemy inaczej - patrz zgrzew 4+4",
    ],
    additionalInfo: [
      "Oczko znajdziesz w folderze PLIKI NA START",
      "Przed umieszczeniem oczka w pliku produkcyjnym upewnij się, że oczko ma taką samą rodzielczość jak plik.",
      "Środek standardowego oczka powinien być oddalony od krawędzi wymiaru brutto o 2cm.",
    ],
    exapmlesMaterials: [
      "bpwl510",
      "mesh270",
      "4+0 bklt",
      "4+0 bkhv",
      "blam510",
    ],
    detailsDw: ["wziąć", "wyciąć"],
    dwExceptions: [""],
    dhInfo: [
      "Wykończenie może występować również na sublimacji ale zwykle łączone jest z wykończeniami tj. np .taśma wzmacniająca od tyłu.",
    ],
  },
  {
    name: "kedar",
    group: "winyle",
    kod: "k",
    description: "Wydruk docięty do formatu + wszyty kedar.",
    detailsDtp: [
      "Na krawędzi, na której występuje dane wykończenie nie powiększamy obrazu.",
      "Jeżeli w danej pozycji występują inne wykończenia na którejś z krawędzi przejdź do nich przed kolejnym krokiem.",
      "Dodaj 1px obrys wokół całej grafiki w kolorze 50/50/50/10.",
      "Dodaj 2 cm białego obszaru roboczego do jednej z krawędzi.",
      "Na dodanym białym obszarze umieść nazwę pliku - skrót Ctrl+F12.",
      "Dodaj kwadracik informujący o rodzaju wysyłki i umieść na nim dzień daty produkcji.",
      "Zapisz plik zgodnie z naszym standardem dodając końcówkę _TwojeInicjały_RIP",
    ],
    dtpExceptions: [],
    additionalInfo: [
      "Kedar to jedno z nielicznych wykończeń przy ktorych nie powiększamy obrazu.",
    ],
    exapmlesMaterials: ["bpwl510", "flg115B", "bkhv640", "bmat215", "mesh270"],
    detailsDw: ["wziąć", "wyciąć"],
    dwExceptions: [""],
  },
  {
    name: "kedar",
    group: "sublimacja",
    kod: "k",
    description: "Wydruk docięty do formatu + wszyty kedar.",
    detailsDtp: [
      "Na krawędzi, na której występuje dane wykończenie nie powiększamy obrazu.",
      "Jeżeli w danej pozycji występują inne wykończenia na którejś z krawędzi przejdź do nich przed kolejnym krokiem.",
      "Dodaj 1px obrys wokół całej grafiki w kolorze 50/50/50/10.",
      "Dodaj 2 cm białego obszaru roboczego do jednej z krawędzi.",
      "Na dodanym białym obszarze umieść nazwę pliku - skrót Ctrl+F12.",
      "Dodaj kwadracik informujący o rodzaju wysyłki i umieść na nim dzień daty produkcji.",
      "Zapisz plik zgodnie z naszym standardem dodając końcówkę _TwojeInicjały_RIP",
    ],
    dtpExceptions: [],
    additionalInfo: [
      "Kedar to jedno z nielicznych wykończeń przy ktorych nie powiększamy obrazu.",
    ],
    exapmlesMaterials: ["bpwl510", "flg115B", "bkhv640", "bmat215", "mesh270"],
    detailsDw: ["wziąć", "wyciąć"],
    dwExceptions: [""],
  },
  {
    name: "szycie",
    group: "sublimacja",
    kod: "s",
    description: "Materiał zawijany i przeszywany na maszynie.",
    detailsDtp: [
      "Na dodanym białym obszarze umieść nazwę pliku - skrót Ctrl+F12.",
      "Dodaj kwadracik informujący o rodzaju wysyłki i umieść na nim dzień daty produkcji.",
      "Zapisz plik zgodnie z naszym standardem dodając końcówkę _TwojeInicjały_RIP",
    ],
    dtpExceptions: [],
    additionalInfo: [""],
    exapmlesMaterials: [],
    detailsDw: [],
    dwExceptions: [""],
  },
  {
    name: "szycie",
    group: "winyle",
    kod: "s",
    description: "Materiał zawijany i przeszywany na maszynie.",
    detailsDtp: [
      "Na dodanym białym obszarze umieść nazwę pliku - skrót Ctrl+F12.",
      "Dodaj kwadracik informujący o rodzaju wysyłki i umieść na nim dzień daty produkcji.",
      "Zapisz plik zgodnie z naszym standardem dodając końcówkę _TwojeInicjały_RIP",
    ],
    dtpExceptions: [],
    additionalInfo: [""],
    exapmlesMaterials: [],
    detailsDw: [],
    dwExceptions: [""],
  },
  {
    name: "oczka w narożnikach",
    group: "winyle",
    kod: "on",
    description: "Pochodna wykończenia oczka.",
    detailsDtp: ["Patrz wykończenie: oczka"],
    dtpExceptions: [],
    additionalInfo: [""],
    exapmlesMaterials: [],
    detailsDw: [],
    dwExceptions: [""],
    dhInfo: ["Patrz wykończenie: oczka"],
  },
  {
    name: "oczka w narożnikach + zgrzew",
    group: "winyle",
    kod: "onz",
    description: "Pochodna wykończenia oczka + zgrzew.",
    detailsDtp: ["Patrz wykończenie: oczka + zgrzew"],
    dtpExceptions: [],
    additionalInfo: [""],
    exapmlesMaterials: [],
    detailsDw: [],
    dwExceptions: [""],
    dhInfo: ["Patrz wykończenie: oczka + zgrzew"],
  },
  {
    name: "oczka w narożnikach + szycie",
    group: "winyle",
    kod: "onz",
    description: "Pochodna wykończenia oczka + szycie.",
    detailsDtp: ["Patrz wykończenie: oczka + szycie"],
    dtpExceptions: [],
    additionalInfo: [""],
    exapmlesMaterials: [],
    detailsDw: [],
    dwExceptions: [""],
    dhInfo: ["Patrz wykończenie: oczka + szycie"],
  },
  {
    name: "podwójny zgrzew",
    group: "winyle",
    kod: "pz",
    description: "Krawędzie zaginane dwukrotnie i zgrzewane.",
    detailsDtp: ["Podwójny zgrzew"],
    dtpExceptions: [],
    additionalInfo: [""],
    exapmlesMaterials: [],
    detailsDw: [],
    dwExceptions: [""],
    dhInfo: ["Krawędzie zaginane dwukrotnie i zgrzewane."],
  },
  {
    name: "podwójny zgrzew + oczka",
    group: "winyle",
    kod: "opz",
    description:
      "Krawędzie zaginane dwukrotnie i zgrzewane + oczka na zgrzewie",
    detailsDtp: [
      "Patrz wykończenie: podwójny zgrzew.",
      "Patrz wykończenie: zgrzew + oczka.",
    ],
    dtpExceptions: [],
    additionalInfo: [""],
    exapmlesMaterials: [],
    detailsDw: [],
    dwExceptions: [""],
    dhInfo: ["Krawędzie zaginane dwukrotnie i zgrzewane + oczka na zgrzewie."],
  },
  {
    name: "szycie + oczka",
    group: "winyle",
    kod: "os",
    description: "Krawędzie zaginane i przeszywane + oczka na szyciu",
    detailsDtp: ["Patrz wykończenie: zgrzew + oczka."],
    dtpExceptions: [],
    additionalInfo: [""],
    exapmlesMaterials: [],
    detailsDw: [],
    dwExceptions: [""],
    dhInfo: ["Krawędzie zaginane i przeszywane + oczka na przeszyciu."],
  },
  {
    name: "szycie + oczka",
    group: "sublimacja",
    kod: "os",
    description:
      "Krawędzie zaginane i przeszywane + oczka na szyciu. Alternatywa do samych oczek i do oczek na taśmie wzmacniającej - lepsza niż same oczka jednak nie tak wytrzymała jak oczka na taśmie.",
    detailsDtp: ["Patrz wykończenie: zgrzew + oczka."],
    dtpExceptions: [],
    additionalInfo: [""],
    exapmlesMaterials: [],
    detailsDw: [],
    dwExceptions: [""],
    dhInfo: [
      "Krawędzie zaginane i przeszywane + oczka na szyciu. Alternatywa do samych oczek i do oczek na taśmie wzmacniającej - lepsza niż same oczka jednak nie tak wytrzymała jak oczka na taśmie.",
    ],
  },
  {
    name: "do kształtu",
    group: "winyle",
    kod: "wk",
    description:
      "Krawędzie wycinane do kształtu tak jak wykończenie do formatu.",
    detailsDtp: ["Patrz wykończenie: zgrzew + oczka."],
    dtpExceptions: [],
    additionalInfo: [""],
    exapmlesMaterials: [],
    detailsDw: [],
    dwExceptions: [""],
    dhInfo: ["Krawędzie wycinane do kształtu tak jak wykończenie do formatu."],
  },
  {
    name: "do kształtu",
    group: "sublimacja",
    kod: "wk",
    description:
      "Krawędzie wycinane do kształtu tak jak wykończenie do formatu. W zależności od rozmiaru i kształtu krawędzie mogą być wycinane na gorąco lub nie.",
    detailsDtp: ["Patrz wykończenie: zgrzew + oczka."],
    dtpExceptions: [],
    additionalInfo: [""],
    exapmlesMaterials: [],
    detailsDw: [],
    dwExceptions: [""],
    dhInfo: [
      "Krawędzie wycinane do kształtu tak jak wykończenie do formatu.",
      "W zależności od rozmiaru i kształtu krawędzie mogą być wycinane na gorąco lub nie.",
    ],
  },
  {
    name: "do kształtu",
    group: "mw",
    kod: "wk",
    description:
      "Krawędzie wycinane do kształtu tak jak wykończenie do formatu. Niektóre grafiki mogą być wycięte do kształtu bez konieczności użycia plotera tnącego.",
    detailsDtp: ["Patrz wykończenie: zgrzew + oczka."],
    dtpExceptions: [],
    additionalInfo: [""],
    exapmlesMaterials: [],
    detailsDw: [],
    dwExceptions: [""],
    dhInfo: [
      "Krawędzie wycinane do kształtu tak jak wykończenie do formatu.",
      "Niektóre grafiki mogą być wycięte do kształtu bez konieczności użycia plotera tnącego.",
    ],
  },
  {
    name: "do kształtu + zgrzew",
    group: "winyle",
    kod: "wkz",
    description: "Krawędzie wycinane do kształtu następnie zgrzewane.",
    detailsDtp: ["Zgrzew do kształtu"],
    dtpExceptions: [],
    additionalInfo: [
      "W większości przypadków wykończenie to zostanie zastąpione wykończeniem do kształtu + szycie - będzie tak, ze względu na dużą problematyczność i niską trwałość zgrzewów innych niż w linii prostej.",
    ],
    exapmlesMaterials: [],
    detailsDw: [],
    dwExceptions: [""],
    dhInfo: [
      "Krawędzie wycinane do kształtu następnie zgrzewane.",
      "W większości przypadków wykończenie to zostanie zastąpione wykończeniem do kształtu + szycie - będzie tak, ze względu na dużą problematyczność i niską trwałość zgrzewów innych niż w linii prostej.",
    ],
  },
  {
    name: "do kształtu + oczka",
    group: "winyle",
    kod: "wko",
    description: "Krawędzie wycinane do kształtu + oczka.",
    detailsDtp: ["Do kształtu + oczka"],
    dtpExceptions: [],
    additionalInfo: [],
    exapmlesMaterials: [],
    detailsDw: [],
    dwExceptions: [""],
    dhInfo: ["Krawędzie wycinane do kształtu + oczka."],
  },
  {
    name: "do kształtu + zgrzew + oczka",
    group: "winyle",
    kod: "wkoz",
    description:
      "Krawędzie wycinane do kształtu, zaginane i zgrzewane, następnie oczkowane. To wykończenie jest możliwe tylko przy określych kształtach - głownie opierających się na liniach prostych. Lepszą i częściej stosowaną alternatywą tego wykończenia jest do kształtu + szycie + oczka.",
    detailsDtp: ["Do kształtu + oczka"],
    dtpExceptions: [],
    additionalInfo: [],
    exapmlesMaterials: [],
    detailsDw: [],
    dwExceptions: [""],
    dhInfo: [
      "Krawędzie wycinane do kształtu, zaginane i zgrzewane, następnie oczkowane.",
      " To wykończenie jest możliwe tylko przy określych kształtach - głownie opierających się na liniach prostych.",
      "Lepszą i częściej stosowaną alternatywą tego wykończenia jest wykończenie do kształtu + szycie + oczka.",
    ],
  },
  {
    name: "do kształtu + oczka",
    group: "sublimacja",
    kod: "wko",
    description: "Krawędzie wycinane do kształtu + oczka.",
    detailsDtp: ["Do kształtu + oczka"],
    dtpExceptions: [],
    additionalInfo: [],
    exapmlesMaterials: [],
    detailsDw: [],
    dwExceptions: [""],
    dhInfo: [
      "Krawędzie wycinane do kształtu + oczka.",
      "Oczka bez dodatkowego wzmocnienia na materiałach sublimacyjnych są mało trwałe - warto dodać wzmocnienie z taśmy wzmacniającej lub ewentualnie przeszycie.",
    ],
  },
  {
    name: "do kształtu + szycie",
    group: "winyle",
    kod: "wks",
    description: "Krawędzie wycinane do kształtu + szycie.",
    detailsDtp: ["Do kształtu + szycie"],
    dtpExceptions: [],
    additionalInfo: ["Przygotowanie tak samo jak do kształtu + zgrzew."],
    exapmlesMaterials: [],
    detailsDw: [],
    dwExceptions: [],
    dhInfo: [
      "Krawędzie wycinane do kształtu + szycie.",
      "Najbezpieczniejsze i najlepsze wzmocnienie krawędzi w przypadku wycinania do kształtu.",
    ],
  },
  {
    name: "do kształtu + szycie",
    group: "sublimacja",
    kod: "wks",
    description: "Krawędzie wycinane do kształtu + szycie.",
    detailsDtp: ["Do kształtu + szycie"],
    dtpExceptions: [],
    additionalInfo: [],
    exapmlesMaterials: [],
    detailsDw: [],
    dwExceptions: [],
    dhInfo: ["Krawędzie wycinane do kształtu + szycie."],
  },
  {
    name: "do kształtu + szycie + oczka",
    group: "winyle",
    kod: "wkos",
    description: "Krawędzie wycinane do kształtu + szycie + oczka.",
    detailsDtp: ["Do kształtu + szycie + oczka"],
    dtpExceptions: [],
    additionalInfo: [],
    exapmlesMaterials: [],
    detailsDw: [],
    dwExceptions: [],
    dhInfo: [
      "Krawędzie wycinane do kształtu + szycie + oczka.",
      "Najbezpieczniejsze i najlepsze wzmocnienie krawędzi w przypadku wycinania do kształtu i oczek.",
    ],
  },
  {
    name: "do kształtu + szycie + oczka",
    group: "sublimacja",
    kod: "wkos",
    description: "Krawędzie wycinane do kształtu + szycie + oczka.",
    detailsDtp: ["Do kształtu + szycie + oczka"],
    dtpExceptions: [],
    additionalInfo: [],
    exapmlesMaterials: [],
    detailsDw: [],
    dwExceptions: [],
    dhInfo: [
      "Krawędzie wycinane do kształtu + szycie + oczka.",
      "Szycie jest kiepskim wzmocnieniem w przypadku oczek na materiałąch sublimacyjnych - zaproponuj wykończenie taśmą wzmacniającą.",
    ],
  },
  {
    name: "rzep",
    group: "winyle",
    kod: "rz",
    description:
      "Krawędzie wycinane do formatu + rzep od spodu lub od strony grafiki.",
    detailsDtp: ["Patrz wykończenie do formatu."],
    dtpExceptions: [],
    additionalInfo: [],
    exapmlesMaterials: [],
    detailsDw: [],
    dwExceptions: [],
    dhInfo: [
      "Krawędzie wycinane do formatu + rzep od spodu lub od strony grafiki.",
      "Rzep w standardzie umieszczany jest na back'u, jeżeli chcesz, aby rzep został umieszony na fronice zawrzyj stosowną informację w szczegółach wykończenia.",
    ],
  },
  {
    name: "rzep",
    group: "sublimacja",
    kod: "rz",
    description:
      "Przyszycie rzepu, następnie zagięcie go na back/front i ponowne przeszycie.",
    detailsDtp: ["Rzep na sublimacji"],
    dtpExceptions: [],
    additionalInfo: [],
    exapmlesMaterials: [],
    detailsDw: [],
    dwExceptions: [],
    dhInfo: [
      "Przyszycie rzepu, następnie zagięcie go na back/front i ponowne przeszycie.",
      "Rzep w standardzie umieszczany jest na back'u, jeżeli chcesz, aby rzep został umieszony na fronice zawrzyj stosowną informację w szczegółach wykończenia.",
    ],
  },
  {
    name: "taśma silikonowa",
    group: "winyle",
    kod: "ts",
    description:
      "Krawędź wzmocniona taśmą silikonową używaną do montażu w specjalnych systemach.",
    detailsDtp: ["Taśma silikonowa"],
    dtpExceptions: [],
    additionalInfo: [],
    exapmlesMaterials: [],
    detailsDw: [],
    dwExceptions: [],
    dhInfo: [
      "Krawędź wzmocniona taśmą silikonową używaną do montażu w specjalnych systemach.",
      "W poligrafie powinien znaleźć się zewnętrzny wymiar ramy - taki rozmiar powinien mieć też plik produkcyjny.",
    ],
  },
  {
    name: "taśma silikonowa",
    group: "sublimacja",
    kod: "ts",
    description:
      "Krawędź wzmocniona taśmą silikonową używaną do montażu w specjalnych systemach.",
    detailsDtp: ["Taśma silikonowa"],
    dtpExceptions: ["Na materiale ledtex dodajemy 0,5 cm w pukncie x."],
    additionalInfo: [],
    exapmlesMaterials: [],
    detailsDw: [],
    dwExceptions: [],
    dhInfo: [
      "Krawędź wzmocniona taśmą silikonową używaną do montażu w specjalnych systemach.",
      "W poligrafie powinien znaleźć się zewnętrzny wymiar ramy - taki rozmiar powinien mieć też plik produkcyjny.",
    ],
  },
  {
    name: "taśma wzmacniająca od przodu",
    group: "sublimacja",
    kod: "twp",
    description:
      "Krawędź wzmocniona złożoną w pół taśmą wzmacniającą. Przypis 'od przodu' jest opcjonalny i możesz spotkać też zapis 'taśma wzmacniająca' i będzie on równoznaczny z powyższym wykończeniem.",
    detailsDtp: ["Taśma wzmacniająca"],
    dtpExceptions: [
      "Zwróć uwagę na szerokość taśmy - standard to 7 cm, czyli na pół 3,5 cm.",
    ],
    additionalInfo: [
      "Taśma wzmacniająca i taśma wzmacniająca od tyłu to dwa różne wykończenia!",
    ],
    exapmlesMaterials: [],
    detailsDw: [],
    dwExceptions: [],
    dhInfo: [
      "Wzmocnienie krawędzi taśmą składaną na pół.",
      "Taśma widoczna jest zarówno na froncie jak i na backu wydruku.",
      "Standardem jest taśma wzmacniająca o szerokości 7 cm, czyli tłumacząc to na język produkcyjny 3,5 cm (taśma jest składana na pół).",
      "Jeżeli chcesz użyć innej szerokości taśmy wpisz stosowną informację w szczegółach wykończenia oraz dodaj do kodu '=szerokość_taśmy_w_cm'",
    ],
  },
  {
    name: "taśma wzmacniająca od tyłu",
    group: "sublimacja",
    kod: "twt",
    description:
      "Krawędź wzmocniona taśmą. Wykończenie niewidoczne od frontu wydruku.",
    detailsDtp: ["Taśma wzmacniająca"],
    dtpExceptions: [
      "Zwróć uwagę na szerokość taśmy - standard to 7 cm, czyli na pół 3,5 cm.",
    ],
    additionalInfo: [
      "Taśma wzmacniająca i taśma wzmacniająca od tyłu to dwa różne wykończenia!",
      "Jeżeli w wykończeniu zawarta jest informacja o innej szerokości niż standardowe 3,5 cm w kodzie powinien znaleźć się dopisek '=szerokość_taśmy_w_cm'.",
    ],
    exapmlesMaterials: [],
    detailsDw: [],
    dwExceptions: [],
    dhInfo: [
      "Wzmocnienie krawędzi taśmą przyszytą od tyłu.",
      "Taśma widoczna jest tylko na backu.",
      "Krawędź wydruku zabezpieczona jest przeszyciem z taśmą dzięki czemu materiał nie ulegnie pruciu.",
    ],
  },
  {
    name: "taśma wzmacniająca od tyłu + oczka",
    group: "sublimacja",
    kod: "twto",
    description:
      "Krawędź wzmocniona taśmą + oczka. Taśma niewidoczna od frontu wydruku.",
    detailsDtp: ["Taśma wzmacniająca od tyłu + oczka"],
    dtpExceptions: [],
    additionalInfo: [
      "Taśma wzmacniająca i taśma wzmacniająca od tyłu to dwa różne wykończenia!",
      "Handlowiec może zamieścić odległość między oczkami w kodzie rozszerzając go o dopisek '=odległość_między_oczkami_w_cm'",
    ],
    exapmlesMaterials: [],
    detailsDw: [],
    dwExceptions: [],
    dhInfo: [
      "Wzmocnienie krawędzi taśmą przyszytą od tyłu + oczka.",
      "Taśma widoczna jest tylko na backu.",
      "Krawędź wydruku zabezpieczona jest przeszyciem z taśmą dzięki czemu materiał nie ulegnie pruciu.",
      "Standardem odległości między oczkami jest 50 cm. Jeżeli chcesz, aby oczka rozmieszczone były w innej odległości rozrzesz kod o dopisek '=odległość_między_oczkami_w_cm' i zawrzyj stosowną informację w szczegółach wykończenia.",
    ],
  },
  {
    name: "cięcie na gorąco",
    group: "sublimacja",
    kod: "cg",
    description:
      "Wycinanie do formatu specjalnym nożem z podgrzewanym ostrzem.",
    detailsDtp: [],
    dtpExceptions: [],
    additionalInfo: ["Wykończenie może być łączone z wycinaniem do kształtu."],
    exapmlesMaterials: [],
    detailsDw: [],
    dwExceptions: [],
    dhInfo: [
      "Wycinanie do formatu nożem na gorąco - zapobiega pruciu się materiału w produktach sublimacyjnych.",
    ],
  },
];

export default wykonczenia;
